#!/bin/sh
shout() { echo "package/compile-doc: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }

#### MAIN

test -d package || barf "no package directory"
exec package/docs -b make ${1+"$@"}

exit 111

